name: Make Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        # Test on multiple operating systems
        os: [ubuntu-latest, macos-latest]
        # Test both Debug and Release configurations
        build_type: [Debug, Release]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Build
      run: make clean all MODE=$(echo "${{ matrix.build_type }}" | tr '[:upper:]' '[:lower:]')

    - name: Run Tests
      run: make runTests MODE=$(echo "${{ matrix.build_type }}" | tr '[:upper:]' '[:lower:]')
